INSERT INTO TAG VALUES (DEFAULT, 'TORONTO');
INSERT INTO TAG VALUES (DEFAULT, 'OTTAWA');
INSERT INTO TAG VALUES (DEFAULT, 'MONTREAL');
INSERT INTO TAG VALUES (DEFAULT, 'GTA');

INSERT INTO CATEGORY VALUES (1, 'DOG');
INSERT INTO CATEGORY VALUES (2, 'CAT');
INSERT INTO CATEGORY VALUES (3, 'FISH');
INSERT INTO CATEGORY VALUES (4, 'HAMSTER');

INSERT INTO PET VALUES (DEFAULT, 1, 'Dog 1', 'dog11.jpg,dog12.jpg,dog13.jpg', DEFAULT);
INSERT INTO PET VALUES (DEFAULT, 1, 'Dog 2', 'dog21.jpg,dog22.jpg,dog23.jpg', DEFAULT);
INSERT INTO PET VALUES (DEFAULT, 2, 'Cat 1', 'cat11.jpg,cat12.jpg,cat13.jpg', DEFAULT);
INSERT INTO PET VALUES (DEFAULT, 2, 'Cat 2', 'cat21.jpg,cat22.jpg,cat23.jpg', DEFAULT);
INSERT INTO PET VALUES (DEFAULT, 2, 'Cat 3', 'cat31.jpg,cat32.jpg,cat33.jpg', DEFAULT);
INSERT INTO PET VALUES (DEFAULT, 3, 'Fish 1', 'fish11.jpg,fish12.jpg', DEFAULT);
INSERT INTO PET VALUES (DEFAULT, 3, 'Fish 2', 'fish21.jpg,fish22.jpg', DEFAULT);

INSERT INTO PET_TAG VALUES (1, 1);
INSERT INTO PET_TAG VALUES (1, 2);
INSERT INTO PET_TAG VALUES (2, 3);
INSERT INTO PET_TAG VALUES (3, 4);