CREATE TABLE CATEGORY (
	ID INT PRIMARY KEY,  
	NAME VARCHAR(50) DEFAULT ''
);

CREATE TABLE TAG (
	ID INT auto_increment PRIMARY KEY,  
	NAME VARCHAR(50) DEFAULT ''
);

CREATE TABLE PET (
	ID INT auto_increment PRIMARY KEY, 
	CATEGORY_ID INT, 
	NAME VARCHAR(50) DEFAULT '', 
	PHOTO_URLS VARCHAR(1000) DEFAULT '', 
	STATUS VARCHAR(20) DEFAULT 'available',
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID)
);

CREATE TABLE PET_TAG (
	PET_ID INT,
	TAG_ID INT
);